# Generated by Django 3.0.5 on 2020-04-10 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_from', models.CharField(max_length=50)),
                ('to', models.CharField(max_length=50)),
                ('message', models.TextField(default=' ')),
                ('video_link', models.CharField(default='https://youtube.com', max_length=200)),
                ('song_description', models.CharField(max_length=200)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
