# Generated by Django 3.0.5 on 2020-04-10 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200410_0506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='_from',
            new_name='post_from',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='to',
            new_name='post_to',
        ),
    ]
