# Generated by Django 3.0.5 on 2020-04-10 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200410_0516'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='embed_link',
            field=models.CharField(default='https://www.youtube.com/embed/video_id?controls=1', max_length=200),
        ),
    ]
