# Generated by Django 3.0.5 on 2020-04-10 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_embed_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video_title',
            field=models.CharField(default='Title of this song', max_length=250),
        ),
    ]
