# Generated by Django 3.0.5 on 2020-04-12 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20200412_0541'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_from_public',
            field=models.CharField(blank=True, default='public user', max_length=50, null=True),
        ),
    ]
